# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check.yaml

permissions: read-all

jobs:
  list:
    name: "List Universe Packages"
    runs-on: ubuntu-latest
    outputs:
      pkgs: ${{ steps.gather.outputs.pkgs }}
    steps:
      - id: gather
        run: |
          {
            echo 'pkgs<<EOF'
            echo "$(curl -sSL https://hubverse-org.r-universe.dev/api/packages \
            | jq -r '[.[]._file] | map(select(. | startswith("hub")))')" 
            echo 'EOF' 
          } >> "$GITHUB_OUTPUT"
      - id: show-output
        run: |
          cat ${{ steps.gather.outputs.pkgs }} | jq
  fetch:
    needs: list
    name: "Fetch Universe Packages"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.list.outputs.pkgs) }}
    steps:
      - id: download
        run: |
          curl -fsSL -o pkg.zip "https://hubverse-org.r-universe.dev/api/snapshot/zip?types=src&packages=${{ matrix.package }}" && \
          ls -l && \
          payload=$(unzip -l pkg.zip | grep tar.gz | sed 's/ \+/,/g' | cut -d, -f 5)
          echo "tarfile=$(basename ${payload})" >> "$GITHUB_OUTPUT"
          mkdir -p ${{ runner.temp }}/package
          unzip -j pkg.zip ${payload}

      - id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}
          path: ${{ steps.download.outputs.tarfile }}

  R-CMD-check:
    needs: [list, fetch]
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.pkg }} | ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        pkg: ${{ fromJSON(needs.list.outputs.pkgs) }}
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: ${{ runner.temp }}
      - id: fetch-pkg
        run: |
          ls -l "${{ runner.temp }}/"
          file "${{ runner.temp }}/${{ matrix.pkg }}"*.tar.gz
          # extract to working dir
          tar -xzvf "${{ runner.temp }}/${{ matrix.pkg }}"*.tar.gz
          # move package contents to working dir
          mv -v "${{ matrix.pkg }}"/* .
          # removing empty folder
          rm -rf "${{ matrix.pkg }}"

      # - uses: r-lib/actions/setup-pandoc@v2

      # - uses: r-lib/actions/setup-r@v2
      #   with:
      #     r-version: ${{ matrix.config.r }}
      #     http-user-agent: ${{ matrix.config.http-user-agent }}
      #     use-public-rspm: true

      # - uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     extra-packages: any::rcmdcheck
      #     needs: check

      # - uses: r-lib/actions/check-r-package@v2
      #   with:
      #     upload-snapshots: true
      #     build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
